site_name: IA & LLMs dans l'Enseignement Supérieur
site_description: Un site avec des ressources pour les étudiant·e·s, enseignant·e·s et chercheur·e·s sur l'IA et les LLMs dans l'enseignement supérieur.
site_author: Théo Leschevin - Département Info Com, IUT Paris Rives de Seine
nav:
  - ⌂ : index.md
  - \? : about.md
  - Etudiant·e·s: et.md
  - Enseignant·e·s: ens.md
  - Chercheur·e·s: ch.md
  - Juridique: jur.md
  - Social : soc.md

theme:
  name: simple-blog
  sidebar: true
  language: fr
  navigation_depth: 3
  logo: img/logo_these_vc.png
  favicon: img/favicon.ico
  theme_style: auto

extra_css:
  - css/extra.css?v=2   # ajouté le numéro poru éviter que le css prenne 10 minutes à rafraichir à chaque fois - GitHub envoyait le cache

extra_javascript:
  - js/toc-spy.js

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption